WIP: Adding documentation on the land-use emulator.
iiasa/message_doc pull request #50
Opened 2020-09-10 14:49 UTC by OFR-IIASA

2020-09-29 14:48 UTC, behnam-zakeri requested changes

2020-09-29 14:48 UTC, behnam-zakeri commented on land_use/emulator.rst
> +The land-use pathways are integrated into MESSAGE using a dedicated set of equations (add link to documentation). At the core, these state that the linear combination of land-use pathways must be equ
This sentence "At the core, these state that the linear combination of land-use pathways must be equal to 1. Therefore, separately" and the following discussion is not clear. Is this the sum of land shares from a total land available?

2021-03-18 15:24 UTC, khaeru commented
Per discussion in Slack, the 2020 documentation will be released now that #51 is in. This PR should be (a) rebased, (b) updated with GLOBIOM documentation from the colleagues who will supply it, and (c) merged in advance of a 2021 release.

2021-04-22 07:01 UTC, OFR-IIASA commented
A few comments from a conversation on slack (from Behnam, Oct. 13, 2020) to improve the documentation of the emulator:
- the legend and labels of some figures can be improved by a more suitable size, also for the figure captions adding more information on each sub-plot when there are multiple figures. (e.g., figure (above) shows..., while below shows...).
- does it make sense to add numbers to equations (Eq. 1, ...)? Then, it's easier to refer to them in the text.
- the costs and prices are in $2005. It may be worth to update this as we are in 2020 and it may be difficult to back-calculate the numbers.

2021-04-23 09:51 UTC, OFR-IIASA commented
@behnam-zakeri I have made changes to address the last set of comments:
- Adjusting all figures and describing the panels in the text
- Switching all units to $2010
- Adding formula references

2021-04-30 14:35 UTC, khaeru approved these changes

2021-04-30 14:35 UTC, khaeru commented
Compiles with no warnings. Thanks @OFR-IIASA!

2021-04-30 14:36 UTC, merged